# Generated by Django 4.2.11 on 2024-05-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diadiemanuong', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together=set(),
        ),
    ]
