# Generated by Django 4.2.11 on 2024-05-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diadiemanuong', '0002_category_image_donhang'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
