# Generated by Django 4.2.11 on 2024-05-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diadiemanuong', '0002_alter_dish_options_alter_dish_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('name', 'restaurant')},
        ),
    ]
