# Generated by Django 4.2.11 on 2024-05-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diadiemanuong', '0003_dish_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
