# Generated by Django 4.2.11 on 2024-05-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diadiemanuong', '0003_delete_userrole_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together=set(),
        ),
    ]
