# Generated by Django 4.2.11 on 2024-05-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diadiemanuong', '0005_alter_orderdetail_user_alter_rating_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.AddField(
            model_name='dish',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
