# Generated by Django 4.2.11 on 2024-05-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diadiemanuong', '0006_order_user_orderdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company_name',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diadiemanuong.dish'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diadiemanuong.restaurant'),
        ),
    ]
