# Generated by Django 4.2.11 on 2024-05-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diadiemanuong', '0009_order_username_alter_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
