# Generated by Django 4.2.11 on 2024-05-10 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diadiemanuong', '0010_alter_rating_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='diadiemanuong.restaurant'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diadiemanuong.order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
