# Generated by Django 4.2.11 on 2024-05-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diadiemanuong', '0010_restaurant_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
