# Generated by Django 4.2.11 on 2024-05-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diadiemanuong', '0012_remove_order_user_remove_orderdetail_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
