# Generated by Django 4.2.11 on 2024-05-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diadiemanuong', '0013_order_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_image',
            field=models.ImageField(null=True, upload_to='restaurants_image/%Y/%m'),
        ),
    ]
