# Generated by Django 4.2.11 on 2024-05-19 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diadiemanuong', '0014_revenue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
